name: Pipeline deployment
on: [push, pull_request]
jobs:
  deployment:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Download the font
        run: |
          mkdir -p ./assets/font
          wget "https://dl.dafont.com/dl/?f=keep_calm" -O ./assets/font/keep_calm.zip
          unzip ./assets/font/keep_calm.zip -d ./assets/font/
      - name: Create a virtual environment
        run: python3 -m venv venv
      - name: Activate the virtual environment
        run: source venv/bin/activate
      - name: Install Pillow dependency
        run: venv/bin/pip install Pillow==12.1.1
      - name: Run it!
        run: venv/bin/python3 keep-calm.py
